project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workout.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workout/urls.py
from django.urls import path

from workout import views

app_name = 'workout'

urlpatterns = [
    path('', views.home, name='home'),
    path('workout/<int:id>/', views.workout, name='workout'),
]

workout/models.py
from django.contrib.auth.models import User
from django.db import models


class Workout(models.Model):

    title = models.CharField(max_length=50)
    description = models.TextField()
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(blank=True, default='')
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )


def __str__(self):
    return self.title

workout/views.py
from django.shortcuts import get_object_or_404, render

from workout.models import Workout


def home(request):
    workouts = Workout.objects.filter(
        is_published=True,
    ).order_by('-id')

    return render(
        request, 'workout/pages/home.html',
        context={'workout': workouts}
    )


def workout(request, id):
    workout = get_object_or_404(Workout, pk=id, is_published=True)

    return render(
        request, 'workout/pages/workout-view.html',
        context={
            'work': workout,
            'is_detail_page': True,
        }
    )

workout/templates/workout/pages/home.html
{% extends 'global/base.html' %}

{% block title %} Home | {% endblock title %} 

{% block content %}
<div class="main-content main-content-list container">
    {% for work in workout %}
        {% include 'workout/partials/workout.html' %}
    {% empty %}
        <div class="margin">
            <h1>Didn't find workouts here ☠️</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

workout/templates/workout/pages/workout-view.html
{% extends 'global/base.html' %}

{% block title %} {{ workouts.title }} | {% endblock title %}  

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'workout/partials/workout.html' %}
</div>
{% endblock content %}

workout/templates/workout/partials/footer.html
<footer class="main-footer">
    
</footer>

workout/templates/workout/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'global/img/favicon.jpg' %}">
    <link rel="stylesheet" href="{% static 'global/css/style.css' %}">

workout/templates/workout/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'workout:home' %}">
                <span class="main-logo-text">Workout</span>
            </a>
        </h1>
    </div>
</header>

workout/templates/workout/partials/workout.html
<div class="workout workout-list-item">
    {% if work.cover.url is not Null %}
        <div class="workout-cover">
            <a href="{% url 'workout:workout' work.id %}">
                <img src="{{ work.cover.url }}" alt="" />
            </a>
        </div>
    {% endif %}

    <div class="workout-title-container">
        <h2 class="workout-title">
            <a href="{% url 'workout:workout' work.id %}">
                {{ work.title }}
            </a>
        </h2>
    </div>

    {% if is_detail_page is not True %}
        <footer class="workout-footer">
            <a class="workout-read-more button button-dark button-full-width" href="{% url 'workout:workout' work.id %}">
                <i class="fas fa-eye"></i>
                <span>See more details</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="workout-content description">
            <p>
                {{ work.description }}
            </p>
        </div>
        <a class="back" href="{% url 'workout:home' %}"><i class="fas fa-backward"></i> Back</a>
    {% endif %}
</div>